import Head from 'next/head';
import PrimaryNav from '../components/PrimaryNav';
import Wrapper from '../components/Wrapper';
import Header from '../components/Header/Header';
import 'bootstrap/dist/css/bootstrap.css';

export default function Home({
	realStateTypeList,
	kazLocation,
	roomNumber,
	category,
	navs,
}) {
	return (
		<div>
			<Head>
				<title>
					Крыша. Недвижимость в Казахстане — объявления о продаже недвижимости
					Казахстана
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PrimaryNav />
			<div id="fullpage-wrapper" style={{ borderTop: 'solid 0.7px #d2d5d5' }}>
				<Wrapper>
					<Header navs={navs} />
				</Wrapper>
			</div>
		</div>
	);
}

//JSON files:
export async function getStaticProps() {
	//RealState Type:
	const response1 = await fetch(
		'http://localhost:3002/api/get-state-type-list'
	);
	const realStateTypeList = await response1.json();

	//Location:
	const response2 = await fetch('http://localhost:3002/api/get-location');
	const kazLocation = await response2.json();

	//Room number:
	const response3 = await fetch('http://localhost:3002/api/get-room-number');
	const roomNumber = await response3.json();

	//Category:
	const response4 = await fetch('http://localhost:3002/api/get-category');
	const category = await response4.json();

	//Nav-title:
	const response5 = await fetch('http://localhost:3002/api/get-nav-lists');
	const navs = await response5.json();

	return {
		props: { realStateTypeList, kazLocation, roomNumber, category, navs },
	};
}
