import Head from 'next/head';
import PrimaryNav from '../components/PrimaryNav';
import Wrapper from './Wrapper';
import Header from '../components/Header/Header';
import Footer from '../components/Footer';

function HeadFooterWrapper(props) {
	return (
		<div>
			<Head>
				{/* Make title dynamic in fututre */}
				<title>{props.headTitle.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PrimaryNav />
			<div id="fullpage-wrapper" style={{ borderTop: 'solid 0.7px #d2d5d5' }}>
				<Wrapper>
					<Header navs={props.navs} />
					{props.children}
					<Footer />
				</Wrapper>
			</div>
		</div>
	);
}

export default HeadFooterWrapper;
